config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, only: [:index, :show, :edit, :update]
  resources :projects do
    collection do
      get :search
      get :category
    end
    member do
      get :chat
      post 'message' => 'messages#chat'
    end
  end
  post 'like/:project_id' => 'likes#like', as: 'like'
  delete 'unlike/:project_id' => 'likes#unlike', as: 'unlike'
  get 'search' => 'top#search'
  get 'chat-list', to: 'projects#chatlist'
  get 'new_projects' => 'projects#new_projects'
  get 'pick_up' => 'projects#pick_up'
  get "bad_request" => "top#bad_request"
  get "internal_server_error" => "top#internal_server_error"
  root 'top#home'
  match "*anything" => "top#not_found", via: [:get, :post, :patch, :delete]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]

  has_many :projects
  has_many :likes
  has_many :like_projects, through: :likes, source: :project
  has_many :messages

  validates :username, presence: true

  def self.from_omniauth(auth)
    where(provider: auth["provider"], uid: auth["uid"]).first_or_create do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.username = auth["info"]["nickname"]
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def set_image(file)
    if !file.nil?
      file_name = file.original_filename
      type = extension_image(file_name)
      file_name = SecureRandom.urlsafe_base64 + type
      File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
      self.image = file_name
    end
  end

  def extension_image(name)
    extension = File.extname(name).downcase
    case extension
    when ".jpg"
      return ".jpg"
    when ".jpeg"
      return ".jpeg"
    when ".png"
      return ".png"
    when ".gif"
      return ".gif"
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_user!, only:[:show, :edit, :update]
  before_action :correct_user, only:[:edit, :update]
  before_action :set_user, only:[:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
    @projects = @user.projects
    @like_projects = @user.like_projects
  end

  def edit
    @jobs = ["高校生", "大学生", "会社員", "総理大臣", "ウェーイ", "フリーター", "ビジュアル系バンドのボーカル", "マーク・ザッカーバーグ"]
  end

  def update
    file = params[:user][:image]
    @user.set_image(file)

    if @user.update(user_params)
      redirect_to @user, notice: 'ユーザー情報が更新されました'
    else
      redirect_to edit_user_path(@user.id)
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :job, :gender, :introduction, :url)
  end

  def correct_user
    user = User.find(params[:id])
    if !current_user?(user)
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<!-- index.html.erbのrenderの中身 -->
<li><%= link_to user.username, user_path(user.id) %></li>
<%= user.job %>

app/views/users/edit.html.erb
<!-- ユーザー情報編集 -->
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <p><%= @user.errors.count %>件のエラーがあります。</p>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.label :job %>
  <%= f.select :job, @jobs %>
  <%= f.label :gender %>
  <%= f.radio_button :gender, 0 %>男
  <%= f.radio_button :gender, 1 %>女
  <%= f.label :introduction %>
  <%= f.text_area :introduction %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit '更新' %>

<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<ul>
  <%= render @users %>
</ul>

app/views/users/show.html.erb
<!-- ユーザープロフィール -->
	<%= stylesheet_link_tag "users", :media => "all" %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	<%= javascript_include_tag 'jquery.oncssanimationend', 'data-turbolinks-track' => true %>
	<div class="sp-menu sp">
		<ul>
			<li><a href="/projects/new"><i class="fa fa-sticky-note"></i>新規掲載</a></li>
			<li><a href="/search"><i class="fa fa-list"></i>ワード検索</a></li>
			<li><a href="/search"><i class="fa fa-asterisk"></i>カテゴリ検索</a></li>
			<li>
				<%= link_to  user_path(current_user.id) do %>
					<i class="fa fa-user"></i>マイページ
				<% end %>
			</li>
			<li><a href="/chat-list"><i class="fa fa-commenting-o"></i>チャット</a></li>
			<li class="close"><a href="#"><i class="fa fa-times-circle"></i>閉じる</a></li>
		</ul>
	</div>
	<section class="header">
		<div class="header-contents">
			<div class="fix-contents">
				<h4>Worth</h4>
				<!-- phone -->
				<a class="fix-list sp" href="javascript:false">
					<i class="fa fa-bars sp-bar"></i>
				</a>
				<!-- phone -->

				<ul class="fix-list pc">
					<li><a href="/projects/new"><i class="fa fa-sticky-note"></i>新規掲載</a></li>
					<li><a href="/search"><i class="fa fa-search"></i>探す</a></li>
					<li  class="drop-child">
						<a href="#"><i class="fa fa-user"></i>ユーザー<i class="fa fa-caret-down"></i></a>
						<ul class="drop-down">
							<li><hr></li>
							<li>
								<%= link_to 'マイページ', user_path(current_user.id) %>
							</li>
							<li>
								<% if user_signed_in? %>
        							<%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
      							<% else %>
        							<%= link_to 'ログイン', new_user_session_path %>
      							<% end %>
							</li>
						</ul>
					</li>
					<li><a href="/chat-list"><i class="fa fa-commenting-o"></i>チャット</a></li>
				</ul>
			</div>
		</div>
	</section>
	<section class="profile sub-page">
		<%= form_for @user do |f| %>
		<div class="profile-grid">
			<div class="img-icon">
				<% if @user.image %>
  					<%= image_tag "/user_images/#{@user.image}" %>
				<% else %>
  					<img src="<%= asset_path "default.jpg" %>" />
				<% end %>
				<%= f.file_field :image , class:'edit-hide' %>
				<div class="edit-fil edit-hide"><i class="fa fa-camera"></i></div>
			</div>
			<h3 class="user_name not-edit"><%= @user.username %></h3>
			<h3><%= f.text_field :username, class:'user_name edit-hide' %></h3>
			<p class="intro not-edit">
				<%= @user.introduction %>
			</p>
			<%= f.text_area :introduction, class: 'intro edit-hide', rows: '4' %>
			<ul class="another_info">
				<li class="not-edit"><i class="fa fa-cog"></i><%= @user.job %></li>
				<li class="edit-hide"><i class="fa fa-cog"></i><%= f.text_field :job %></li>
				<% unless @user.url == nil %>
				<li class="not-edit"><i class="fa fa-link"></i><%= link_to @user.url, @user.url %></li>
				<% end %>
				<li class="edit-hide"><i class="fa fa-link"></i><%= f.text_field :url %></li>
			</ul>
			<p style="clear: both"></p>
			<% if current_user?(@user) %>
			 	<div class="edit show">
			  		<a href="javascript:false"><i class="fa fa-cogs"></i></a>
			  	</div>
				<div class="edit-mode">
			  		<a href="javascript:false" class="edit-cancel">
			  			<i class="fa fa-times" style="color: red"></i>
			  		</a>
			  		<a href="javascript:false">
			  			<i class="fa fa-check" style="color: blue">
			  				<%= f.submit '更新' ,class:'edit-submit'%>
			  			</i>
			  		</a>
			  	</div>
			<% end %>
		</div>
		<% end %>
	</section>
	<section class="user_projects">
		<ul>
			<li list-data="my-project" class="select">
				<a href="javascript:false"><i class="fa fa-paper-plane"></i>マイプロジェクト</a>
			</li>
			<li list-data="heart-project">
				<a href="javascript:false"><i class="fa fa-heart-o"></i>気になる</a>
			</li>
		</ul>
		<div class="user_projects_contents">

			<div class="main-item-list my-project">
				<% if @projects.empty? %>
					<div class="projects_not_zone show-item">
						<p>not project</p>
					</div>
				<% end %>

				<% @projects.each do |project| %>
					<div class="item-space">
						<div class="main-item">
							<a class="img_link" href="/projects/<%= project.id %>">
								<div class="resize_wra">
									<%= image_tag "/project_images/#{project.image}" %>
								</div>
							</a>
							<h3 class="item-title">
								<%= link_to project.title, project_path(project.id) %>
							</h3>
							<p>
								<i class="fa fa-check-square-o"></i><%= project.caption %>
							</p>
							<p>
								<i class="fa fa-user"></i><%= project.user.username %>
							</p>
							<p>
								<i class="fa fa-tag"></i><%= what_tag(project) %>
							</p>
							<p class="hart">
								<i class="fa fa-heart"></i><%= project.likes.count %>
							</p>
						</div>
					</div>
				<% end %>
			</div>
			<div class="main-item-list heart-project">
				<% if @like_projects.empty? %>
					<div class="projects_not_zone">
						<p>not projects</p>
					</div>
				<% end %>

				<% @like_projects.each do |project| %>
					<div class="item-space">
						<div class="main-item">
							<a class="img_link" href="/projects/<%= project.id %>">
								<div class="resize_wra">
									<%= image_tag "/project_images/#{project.image}" %>
								</div>
							</a>
							<h3 class="item-title">
								<%= link_to project.title, project_path(project.id) %>
							</h3>
							<p>
								<i class="fa fa-check-square-o"></i><%= project.caption %>
							</p>
							<p>
								<i class="fa fa-user"></i><%= project.user.username %>
							</p>
							<p>
								<i class="fa fa-tag"></i><%= what_tag(project) %>
							</p>
							<p class="hart">
								<i class="fa fa-heart"></i><%= project.likes.count %>
							</p>
						</div>
					</div>
				<% end %>
			</div>
			</div>
		</div>
	</section>
	<section class="footer">
		<div class="first">
			<ul>
				<li><a href="/projects/new">プロジェクトを作る</a></li>
				<li><a href="#">Worseについて</a></li>
			</ul>
		</div>
		<div class="second">
			<div class="one-block">
				<h5>Menu</h5>
				<ul>
					<li><a href="/projects/new">プロジェクトを作る</a></li>
					<li><a href="/search">ワード検索</a></li>
					<li><a href="/search">カテゴリ検索</a></li>
					<% if user_signed_in? %>
					<li><%= link_to 'ユーザーページ', user_path(current_user.id) %></li>
					<% end %>
					<li><a href="/chat-list">チャット</a></li>
					<li>
						<% if user_signed_in? %>
        					<%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
      					<% else %>
        					<%= link_to 'ログイン', new_user_session_path %>
      					<% end %>
					</li>
				</ul>
			</div>
			<div class="twe-block">
				<h5>developer</h5>
				<ul>
					<li><a href="https://twitter.com/nyaratakumi">@nyaratakumi</a></li>
					<li><a href="https://twitter.com/_Ghostrick_">@_Ghostrick_</a></li>
					<li><a href="https://twitter.com/Tobira_xiexie">@Tobira_xiexie</a></li>
				</ul>
			</div>
			<div class="three-block">
			</div>
		</div>
		<div class="clear"></div>
	</section>


<script type="text/javascript">
function ThisPhone(){
	var Agent = navigator.userAgent;
    if(Agent.indexOf('iPhone') > 0 || Agent.indexOf('iPod') > 0 || Agent.indexOf('Android') > 0 && Agent.indexOf('Mobile') > 0){
        return true;
    } else if (Agent.indexOf('iPad') > 0 || Agent.indexOf('Android') > 0){
        return true;
    } else {
        return false;
    }
};


function img_resize(){
   	
};
function item_resize() {
	bigger = 0;
	$(".main-item").each(function(){

		prev_posi = $(this).position().top;

		this_height = $(this).outerHeight();

		if(this_height > bigger)
			bigger = this_height;
	});
	$(".main-item").css({height: bigger + "px"});
}

$(window).load(function () {
    item_resize();

    $('.heart-project').css({display:'none'});

	if(ThisPhone() == false){
    	$(window).on('resize',function() {
    		item_resize();
		});
	}

});


$(function(){

	/* ------------------------------------------------- */
    /* ------------------------------------------------- */
    /* 					menu 	 						 */
    /* ------------------------------------------------- */
    /* ------------------------------------------------- */
	$(window).scroll(function (){
        var header_top = $(".fix-contents").offset().top;
        if( header_top <= $(this).scrollTop() ){
        	$('.fix-contents').addClass('fix');
        }
        if(  $(this).scrollTop() == 0 )  {
        	$('.fix-contents').removeClass('fix');
        }
    });

	var sp_menu = $('.sp-menu');

	$('.fix-list.sp').on('click',function(){
		if(!$(sp_menu).hasClass('show')){
			$(sp_menu).addClass('show');
			$('.fix-contents').addClass('fix');
		} else {
			$(sp_menu).removeClass('show');
			$('.fix-contents').removeClass('fix');
		}
	});

	$('.sp-menu > ul > .close').on('click',function(){
		$(sp_menu).removeClass('show');
		$('.fix-contents').removeClass('fix');
	});


    $('.drop-child').hover(
    	function(){
    		var targetEl = $(this).find('ul');
    		targetEl.css({display:'block'});
			targetEl.find('li').animate({top:'0',opacity:'1'},300);
    	},function(){
    		var targetEl = $(this).find('ul');
       		targetEl.find('li').css({top:'-10px',opacity:'0'});
    		targetEl.css({'display':'none'});
    	}
    );

    /* ------------------------------------------------- */
    /* 					item grid						 */
    /* ------------------------------------------------- */

    // img contents


	// tab contents

	$('.my-project .item-space').addClass('show-item');

	$('.user_projects ul li').on('click',function(){

		$(this).siblings().removeClass('select');
		$(this).addClass('select');

		list_data = $(this).attr('list-data');

		$('.' + list_data).siblings().find( '.item-space , .projects_not_zone' ).removeClass('show-item').onCSSTransitionEnd(function(){

			$('.' + list_data).siblings().css({display:'none'});
			$('.' + list_data).css({display:'block'});
			setTimeout(function(){
				$('.' + list_data).find( '.item-space , .projects_not_zone' ).addClass('show-item');
			},10);

		});

	});

	// edit mode

	var edit_hide = $('.edit-hide');
	var not_edit = $('.not-edit');
	$('.edit').on('click',function(){
		$(edit_hide).removeClass('edit-hide');
		$(not_edit).addClass('edit-hide');

		$('.show.edit').removeClass('show');
		setTimeout(function(){
			$('.edit').css({display:'none'});
			$('.edit-mode').css({display:'block'});
			setTimeout(function(){
				$('.edit-mode').addClass('show');
			},10);
		},500);
	});


	$('.edit-cancel').on('click',function(){
		$(edit_hide).addClass('edit-hide');
		$(not_edit).removeClass('edit-hide');
		$('.img-icon img').attr('src',now_icon_url);

		$('.show.edit-mode').removeClass('show');
		setTimeout(function(){
			$('.edit-mode').css({display:'none'});
			$('.edit').css({display:'block'});
			setTimeout(function(){
				$('.edit').addClass('show');
			},10);
		},500);
	});


	//icon pre
	var now_icon_url = $('.img-icon img').attr('src');

 	$('input[type=file]').change(function() {
	    var file = $(this).prop('files')[0];

    	if (! file.type.match('image.*')) {
      		$(this).val('');
      		return;
    	}

    	var file_reader = new FileReader();
    	file_reader.onload = function() {
      		$('.img-icon img').attr('src',file_reader.result);
    	}
    	file_reader.readAsDataURL(file);
	});

});
</script>