config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, only: [:index, :show, :edit, :update]
  resources :projects do
    collection do
      get :search
      get :category
    end
    member do
      get :chat
      post 'message' => 'messages#chat'
    end
  end
  post 'like/:project_id' => 'likes#like', as: 'like'
  delete 'unlike/:project_id' => 'likes#unlike', as: 'unlike'
  get 'search' => 'top#search'
  get 'chat-list', to: 'projects#chatlist'
  get 'new_projects' => 'projects#new_projects'
  get 'pick_up' => 'projects#pick_up'
  get "bad_request" => "top#bad_request"
  get "internal_server_error" => "top#internal_server_error"
  root 'top#home'
  match "*anything" => "top#not_found", via: [:get, :post, :patch, :delete]
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :likes
  has_many :like_users, through: :likes, source: :user
  has_many :projects
  has_one :room ,dependent: :destroy


  validates :title, presence: true
  validates :description, presence: true
  validates :user_id, presence: true
  validates :image, presence: true
  validates :caption, presence: true
  validates :caption, length: { maximum: 50 }

  def set_project_image(file)
    if !file.nil?
      file_name = file.original_filename
      type = extension_img(file_name)
      file_name = SecureRandom.urlsafe_base64 + type
      File.open("public/project_images/#{file_name}", 'wb'){|f| f.write(file.read)}
      # File.open("../#{file_name}", 'wb'){|f| f.write(file.read)}
      self.image = file_name
    end
  end

  def extension_img(name)
    extension = File.extname(name).downcase
    case extension
    when ".jpg"
      return ".jpg"
    when ".jpeg"
      return ".jpeg"
    when ".png"
      return ".png"
    when ".gif"
      return ".gif"
    end
  end

  class << self
    def search(query)
      rel = order(:created_at)
      if query.present?
        rel = rel.where("title LIKE ? OR caption LIKE ?", "%#{query}%", "%#{query}%")
      end
      rel
    end

    def category(tag)
      rel = order(:created_at)
      rel = rel.where(business: 1) if tag == "ビジネス"
      rel = rel.where(social: 1) if tag == "社会貢献"
      rel = rel.where(music: 1) if tag == "音楽"
      rel = rel.where(art: 1) if tag == "アート"
      rel = rel.where(event: 1) if tag == "イベント"
      rel = rel.where(product: 1) if tag == "プロダクト"
      rel = rel.where(app: 1) if tag == "アプリ"
      rel = rel.where(game: 1) if tag == "ゲーム"
      rel = rel.where(food: 1) if tag == "フード"
      rel = rel.where(global: 1) if tag == "グローバル"
      rel = rel.where(fashion: 1) if tag == "ファッション"
      rel = rel.where(movie: 1) if tag == "ムービー"
      rel = rel.where(book: 1) if tag == "本"
      rel
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_user!, only:[:new, :edit, :update, :destroy, :chat, :chatlist]
  before_action :correct_project, only:[:edit, :update, :destroy]


  def index
    @options = ["ビジネス", "社会貢献", "音楽", "アート", "イベント", "プロダクト", "アプリ", "ゲーム", "フード", "グローバル", "ファッション", "ムービー", "本"]
    @projects = Project.all
  end


  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.build(project_params)
    file = params[:project][:image]
    @project.set_project_image(file)

    if @project.save
      room = Room.new
      room.channel = SecureRandom.urlsafe_base64
      room.project_id = @project.id
      room.save
      redirect_to @project, notice: '新規プロジェクトを募集開始しました'
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    file = params[:project][:image]
    @project.set_project_image(file)

    if @project.update(project_params)
      redirect_to @project, notice: 'プロジェクト情報が更新されました'
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to user_path(current_user)
  end

  def search
    @options = ["ビジネス", "社会貢献", "音楽", "アート", "イベント", "プロダクト", "アプリ", "ゲーム", "フード", "グローバル", "ファッション", "ムービー", "本"]
    @projects = Project.search(params[:q])
    @result = params[:q]
    @search_mode = 'keyword'
    render :index
  end

  def category
    @options = ["ビジネス", "社会貢献", "音楽", "アート", "イベント", "プロダクト", "アプリ", "ゲーム", "フード", "グローバル", "ファッション", "ムービー", "本"]
    @projects = Project.category(params[:p][:category])
    @result = params[:p][:category]
    @search_mode = 'category'
    render :index
  end

  def chat
    @room = Room.find_by(project_id: params[:id])
    @owner = @room.owner
    @messages = Message.where(room_id: @room.id)
  end

  def chatlist
    @lists = List.where(user_id: current_user.id)
  end

  def new_projects
    @projects = Project.all.order("created_at DESC").limit(50)
    @title = '新着プロジェクト'
    render :index
  end

  def pick_up
    @projects = Project.order("RANDOM()").limit(50)
    @title = 'ピックアップ'
    render :index
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :caption,
     :business, :social, :music, :art, :event, :product, :app, :game,
      :food, :global, :fashion, :movie, :book)
  end

  def correct_project
    project = Project.find(params[:id])
    if !current_user?(project.user)
      redirect_to root_path, notice: 'リクエストが不正じゃゴラァァァ！！'
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def category_intro(res)
  		case res
  			when 'ビジネス' then
  				'ビジネスって感じよ'
  			when '社会貢献' then
  				'ボランティアとか'
  			when '音楽' then
  				'Hey!! Mr.Music!!'
  			when 'アート' then
  				'絵を描こう'
  			when 'イベント' then
  				'わっしょい、祭りじゃ'
  			when 'プロダクト' then
  				'おおお？'
  			when 'アプリ' then
  				'3コンボ'
  			when 'フード' then
  				'おいひいでっす'
  			when 'ゲーム' then
  				'ナナシスは神'
  			when 'グローバル' then
  				'はろー、しぇいしぇい'
  			when 'ファッション' then
  				'オオォォォォかわいい'
  			when 'ムービー' then
  				'貞子とかね'
  			when '本' then
  				'小説はいいぞ'
  			else
  				''
  		end
  	end

		def project_detail(project)
			Project.find(project)
		end
end

app/views/projects/_list.html.erb
<% project = project_detail(list.project_id) %>
<a href="/projects/<%= list.project_id %>/chat" class="list-item">
    <div class="img-wra">
        <%= image_tag "/project_images/#{project.image}" %>
    </div>
    <div class="text-wra">
        <h6 class="project-title"><%= project.title %></h6>
        <span class="project-owner">
            <i class="fa fa-user sq" aria-hidden="true"></i>
            <%= project.user.username %>
        </span>
    </div>
</a>

app/views/projects/_project.html.erb
					<div class="item-space">
						<div class="main-item">
							<a class="img_link" href="/projects/<%= project.id %>">
								<div class="resize_wra">
									<%= image_tag "/project_images/#{project.image}"%>
								</div>
							</a>
							<h3 class="item-title">
								<%= link_to project.title, project_path(project.id) %>
							</h3>
							<p>
								<i class="fa fa-check-square-o"></i><%= project.caption %>
							</p>
							<p>
								<i class="fa fa-user"></i><%= project.user.username %>
							</p>
							<p>
								<i class="fa fa-tag"></i><%= what_tag(project) %>
							</p>
							<p class="hart">
								<i class="fa fa-heart"></i><%= project.likes.count %>
							</p>
						</div>
					</div>

app/views/projects/chat.html.erb
    <%= stylesheet_link_tag "chat", :media => "all" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'jquery.oncssanimationend', 'data-turbolinks-track' => true %>
    <div class="sp-menu sp">
      <ul>
          <li><a href="/projects/new"><i class="fa fa-sticky-note"></i>新規掲載</a></li>
          <li><a href="/search"><i class="fa fa-list"></i>ワード検索</a></li>
          <li><a href="/search"><i class="fa fa-asterisk"></i>カテゴリ検索</a></li>
          <li>
              <%= link_to  user_path(current_user.id) do %>
              <i class="fa fa-user"></i>マイページ
              <% end %>
          </li>
          <li><a href="/chat-list"><i class="fa fa-commenting-o"></i>チャット</a></li>
          <li class="close"><a href="#"><i class="fa fa-times-circle"></i>閉じる</a></li>
      </ul>
    </div>
        <section class="header">
        <div class="header-contents">
            <div class="fix-contents">
                <h4>Worth</h4>
                <!-- phone -->
                <a class="fix-list sp" href="javascript:false">
                    <i class="fa fa-bars sp-bar"></i>
                </a>
                <!-- phone -->

                <ul class="fix-list pc">
                    <li><a href="/projects/new"><i class="fa fa-sticky-note"></i>新規掲載</a></li>
                    <li><a href="/search"><i class="fa fa-search"></i>探す</a></li>
                    <li  class="drop-child">
                        <a href="#"><i class="fa fa-user"></i>ユーザー<i class="fa fa-caret-down"></i></a>
                        <ul class="drop-down">
                            <li><hr></li>
                            <li>
                                <%= link_to 'マイページ', user_path(current_user.id) %>
                            </li>
                            <li>
                                <% if user_signed_in? %>
                                    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
                                <% else %>
                                    <%= link_to 'ログイン', new_user_session_path %>
                                <% end %>
                            </li>
                        </ul>
                    </li>
                    <li><a href="/chat-list"><i class="fa fa-commenting-o"></i>チャット</a></li>
                </ul>
            </div>
        </div>
    </section>
    <section class="chat">
        <div class="chat-wra">
            <h5>Chat</h5>
            <div class="msg-wra">
                <% @messages.each do |message| %>
                    <div class="message-box">
                    <% if message.user.image %>
                      <%= image_tag "/user_images/#{message.user.image}" %>
                    <% else %>
                      <img src="<%= asset_path "default.jpg" %>" />
                    <% end %>
                    <p class="msg-name"><%= message.user.username %></p>
                    <p class="msg-text"><%= message.body %></p>
                    </div>
                <% end %>
            </div>
        </div>
        <%= form_tag(:message_project, :remote => true) do %>
        <div class="send-wra">
            <textarea rows="3" name="message"></textarea>
            <div class="send">
            <%= submit_tag 'send' %>
                <p><i class="fa fa-paper-plane" aria-hidden="true"></i>send</p>
            </div>
        </div>
        <% end %>

        <div class="chat-info">
            <div class="icon-wra">
                <i class="fa fa-info-circle" aria-hidden="true"></i>
            </div>
            <div class="info-text">
                <h6 class="project-name"><%= @room.project.title %></h6>
                <p class="project-caption">
                    <span>
                        <i class="fa fa-check-square-o sq"></i>
                        <%= @room.project.caption %>
                    </span>
                </p>
                <p class="owner-name">
                    <span>
                        <i class="fa fa-user sq" aria-hidden="true"></i>
                        <%= link_to @owner.username, user_path(@owner) %>
                    </span>
                </p>
            </div>
            <p class="view-project">
                <%= link_to 'プロジェクトを見る ', project_path(@room.project.id) %>
                <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
            </p>
        </div>

    </section>
    <section class="footer">
        <div class="first">
            <ul>
                <li><a href="#">プロジェクトを作る</a></li>
                <li><a href="#">Worseについて</a></li>
            </ul>
        </div>
        <div class="second">
            <div class="one-block">
                <h5>Menu</h5>
                <ul>
                    <li><a href="/projects/new">プロジェクトを作る</a></li>
                    <li><a href="/search">ワード検索</a></li>
                    <li><a href="/search">カテゴリ検索</a></li>
                    <li><%= link_to 'ユーザーページ', user_path(current_user.id) %></li>
                    <li><a href="/chat-list">チャット</a></li>
                    <li>
                        <% if user_signed_in? %>
                            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
                        <% else %>
                            <%= link_to 'ログイン', new_user_session_path %>
                        <% end %>
                    </li>
                </ul>
            </div>
            <div class="twe-block">
                <h5>developer</h5>
                <ul>
                    <li><a href="https://twitter.com/nyaratakumi">@nyaratakumi</a></li>
                    <li><a href="https://twitter.com/_Ghostrick_">@_Ghostrick_</a></li>
                    <li><a href="https://twitter.com/Tobira_xiexie">@Tobira_xiexie</a></li>
                </ul>
            </div>
            <div class="three-block">
            </div>
        </div>
        <div class="clear"></div>
    </section>

    <script src="https://js.pusher.com/3.1/pusher.min.js"></script>
    <script type="text/javascript">



$(function(){

    /* ------------------------------------------------- */
    /* ------------------------------------------------- */
    /*                  menu                             */
    /* ------------------------------------------------- */
    /* ------------------------------------------------- */
    $(window).scroll(function (){
        var header_top = $(".fix-contents").offset().top;
        if( header_top <= $(this).scrollTop() ){
            $('.fix-contents').addClass('fix');
        }
        if(  $(this).scrollTop() == 0 )  {
            $('.fix-contents').removeClass('fix');
        }
    });

    var sp_menu = $('.sp-menu');

    $('.fix-list.sp').on('click',function(){
        if(!$(sp_menu).hasClass('show')){
            $(sp_menu).addClass('show');
            $('.fix-contents').addClass('fix');
        } else {
            $(sp_menu).removeClass('show');
            $('.fix-contents').removeClass('fix');
        }
    });

    $('.sp-menu > ul > .close').on('click',function(){
        $(sp_menu).removeClass('show');
        $('.fix-contents').removeClass('fix');
    });


    $('.drop-child').hover(
        function(){
            var targetEl = $(this).find('ul');
            targetEl.css({display:'block'});
            targetEl.find('li').animate({top:'0',opacity:'1'},300);
        },function(){
            var targetEl = $(this).find('ul');
            targetEl.find('li').css({top:'-10px',opacity:'0'});
            targetEl.css({'display':'none'});
        }
    );


    var pusher = new Pusher('a774d21cd6a18ea2d2f0', {
     encrypted: true
    });
    var channel = pusher.subscribe('<%= @room.channel %>');

    var msg_box = $('.msg-wra');
/*
    $('form .send').on('click',function(){
        $('form textarea').val("");
    });
*/

    channel.bind('chat_event', function(data) {
      if (data.user.image) {
        icon = '<img src="/user_images/' + data.user.image + '">'
      } else {
        icon = '<img src="<%= asset_path "default.jpg" %>" />'
      }

      append_content = $('<div class="message-box">' +
                              icon +
                              '<p class="msg-name">' + data.user.username + '</p>' +
                              '<p class="msg-text">' + data.message + '</p>' +
                          '</div>');

      $(msg_box).append(append_content);
    });
});
</script>

app/views/projects/edit.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <p><%= @project.errors.count %>件のエラーがあります。</p>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.text_area :description %>
  キャプション(50文字以内)<%= f.text_area :caption %>

  <%= f.check_box :business %>ビジネス・スタートアップ
  <%= f.check_box :social %>社会貢献
  <%= f.check_box :music %>音楽
  <%= f.check_box :art %>アート
  <%= f.check_box :event %>イベント
  <%= f.check_box :product %>プロダクト
  <%= f.check_box :app %>アプリ
  <%= f.check_box :game %>ゲーム
  <%= f.check_box :food %>フード
  <%= f.check_box :global %>グローバル
  <%= f.check_box :fashion %>ファッション
  <%= f.check_box :movie %>ムービー
  <%= f.check_box :book %>本

  <%= f.submit '更新！' %>
<% end %>

app/views/projects/show.html.erb
    <%= stylesheet_link_tag "project", :media => "all" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'jquery.oncssanimationend', 'data-turbolinks-track' => true %>
    <div class="sp-menu sp">
      <ul>
          <li><a href="/projects/new"><i class="fa fa-sticky-note"></i>新規掲載</a></li>
          <li><a href="/search"><i class="fa fa-list"></i>ワード検索</a></li>
          <li><a href="/search"><i class="fa fa-asterisk"></i>カテゴリ検索</a></li>
          <li><% if user_signed_in? %>
              <%= link_to  user_path(current_user.id) %>
              <i class="fa fa-user"></i>マイページ
              <% end %>
          </li>
          <li><a href="/chat-list"><i class="fa fa-commenting-o"></i>チャット</a></li>
          <li class="close"><a href="#"><i class="fa fa-times-circle"></i>閉じる</a></li>
      </ul>
    </div>
        <section class="header">
        <div class="header-contents">
            <div class="fix-contents">
                <h4>Worth</h4>
                <!-- phone -->
                <a class="fix-list sp" href="javascript:false">
                    <i class="fa fa-bars sp-bar"></i>
                </a>
                <!-- phone -->

                <ul class="fix-list pc">
                    <li><a href="/projects/new"><i class="fa fa-sticky-note"></i>新規掲載</a></li>
                    <li><a href="/search"><i class="fa fa-search"></i>探す</a></li>
                    <li  class="drop-child">
                        <a href="#"><i class="fa fa-user"></i>ユーザー<i class="fa fa-caret-down"></i></a>
                        <ul class="drop-down">
                            <li><hr></li>
                            <% if user_signed_in? %>
                            <li>
                                <%= link_to 'マイページ', user_path(current_user.id) %>
                            </li>
                            <% end %>
                            <li>
                                <% if user_signed_in? %>
                                    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
                                <% else %>
                                    <%= link_to 'ログイン', new_user_session_path %>
                                <% end %>
                            </li>
                        </ul>
                    </li>
                    <li><a href="/chat-list"><i class="fa fa-commenting-o"></i>チャット</a></li>
                </ul>
            </div>
        </div>
    </section>
    <section class="project">

        <div class="project-wrapper">
            <h3 class="project-title"><%= @project.title %></h3>
            <div class="project-img">
                <div class="img-wra"><%= image_tag "/project_images/#{@project.image}" %></div>
            </div>
            <div class="project-status">
                <ul>
                    <li class="tag"><i class="fa fa-tag" aria-hidden="true"></i><%= what_tag(@project) %></li>
                    <li class="date"><i class="fa fa-clock-o" aria-hidden="true"></i><%= @project.created_at.strftime('%Y年%m月%d日') %></li>
                    <li class="user"><i class="fa fa-user" aria-hidden="true"></i><%= link_to @project.user.username, user_path(@project.user) %></li>
                </ul>
            </div>
            <div class="project-text">
                <%= @project.description %>
            </div>
            <div class="action-btn">
                <% if user_signed_in? %>
                    <% if current_user.likes.find_by(project_id: @project.id) %>
                        <div class="del">
                            <%= link_to unlike_path(@project.id), method: :delete do %>
                                <i class="fa fa-heart" aria-hidden="true"></i>いいね！を取り消す
                            <% end %>
                        </div>
                    <% else %>
                        <div class="like">
                            <%= link_to like_path(@project.id), method: :post do%>
                                <i class="fa fa-heart" aria-hidden="true"></i>いいね！
                            <% end %>
                        </div>
                    <% end %>
                    <div class="chat"><a href="/projects/<%= @project.id %>/chat"><i class="fa fa-comment" aria-hidden="true"></i>チャット</a></div>
                    <% if current_user?(@project.user) %>
                      <div class="trash">
                        <%= link_to project_path(@project.id), method: "delete", "data-confirm" => "本当に削除しますか？" do %>
                            <i class="fa fa-trash-o" aria-hidden="true"></i>削除
                    <% end %>
                    </div>
                <% end %>
              <% end %>
            </div>
        </div>
        <div class="owner-info">
            <div class="img-wra">
              <% if @project.user.image %>
                  <%= image_tag "/user_images/#{@project.user.image}" %>
              <% else %>
                  <img src="<%= asset_path "default.jpg" %>" />
              <% end %>
            </div>
            <div class="info-text">
                <h6 class="owner-name"><%= @project.user.username %></h6>
                <p class="project-count">
                    <span>
                        <i class="fa fa-file-text-o sq" aria-hidden="true"></i>
                        他に<%=  @project.user.projects.count - 1 %>件のプロジェクトがあります
                    </span>
                </p>
                <p class="owner-job">
                    <span>
                        <i class="fa fa-cog sq" aria-hidden="true"></i>
                        <%= @project.user.job %>
                    </span>
                </p>
            </div>
            <p class="view-profile">
                <%= link_to 'プロフィールを見る', user_path(@project.user) %>
                <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
            </p>
        </div>
    </section>
    <section class="footer">
        <div class="first">
            <ul>
                <li><a href="/projects/new">プロジェクトを作る</a></li>
                <li><a href="#">Worthについて</a></li>
            </ul>
        </div>
        <div class="second">
            <div class="one-block">
                <h5>Menu</h5>
                <ul>
                    <li><a href="/projects/new">プロジェクトを作る</a></li>
                    <li><a href="/search">ワード検索</a></li>
                    <li><a href="/search">カテゴリ検索</a></li>
                    <% if user_signed_in? %>
                    <li><%= link_to 'ユーザーページ', user_path(current_user.id) %></li>
                    <% end %>
                    <li><a href="/chat-list">チャット</a></li>
                    <li>
                        <% if user_signed_in? %>
                            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
                        <% else %>
                            <%= link_to 'ログイン', new_user_session_path %>
                        <% end %>
                    </li>
                </ul>
            </div>
            <div class="twe-block">
                <h5>developer</h5>
                <ul>
                    <li><a href="https://twitter.com/nyaratakumi">@nyaratakumi</a></li>
                    <li><a href="https://twitter.com/_Ghostrick_">@_Ghostrick_</a></li>
                    <li><a href="https://twitter.com/Tobira_xiexie">@Tobira_xiexie</a></li>
                </ul>
            </div>
            <div class="three-block">
            </div>
        </div>
        <div class="clear"></div>
    </section>

    <script type="text/javascript">



$(function(){

    /* ------------------------------------------------- */
    /* ------------------------------------------------- */
    /*                  menu                             */
    /* ------------------------------------------------- */
    /* ------------------------------------------------- */
    $(window).scroll(function (){
        var header_top = $(".fix-contents").offset().top;
        if( header_top <= $(this).scrollTop() ){
            $('.fix-contents').addClass('fix');
        }
        if(  $(this).scrollTop() == 0 )  {
            $('.fix-contents').removeClass('fix');
        }
    });

    var sp_menu = $('.sp-menu');

    $('.fix-list.sp').on('click',function(){
        if(!$(sp_menu).hasClass('show')){
            $(sp_menu).addClass('show');
            $('.fix-contents').addClass('fix');
        } else {
            $(sp_menu).removeClass('show');
            $('.fix-contents').removeClass('fix');
        }
    });

    $('.sp-menu > ul > .close').on('click',function(){
        $(sp_menu).removeClass('show');
        $('.fix-contents').removeClass('fix');
    });


    $('.drop-child').hover(
        function(){
            var targetEl = $(this).find('ul');
            targetEl.css({display:'block'});
            targetEl.find('li').animate({top:'0',opacity:'1'},300);
        },function(){
            var targetEl = $(this).find('ul');
            targetEl.find('li').css({top:'-10px',opacity:'0'});
            targetEl.css({'display':'none'});
        }
    );


    /* ----------------------- */
    /*         text            */
    /* ----------------------- */
    preview_text = $(".project-text").text();

    preview_text = preview_text.replace(/\n/g,"<br>\n");
    preview_text = preview_text.replace(/\*(.*)\*/g, '<span class="bold">$1</span>');
    preview_text = preview_text.replace(/\###(.*)\<br>/g, '<h6 class="small-title">$1</h6>');
    preview_text = preview_text.replace(/\##(.*)\<br>/g, '<h6 class="min-title">$1</h6>');
    preview_text = preview_text.replace(/\#(.*)\<br>/g, '<h5 class="min-title">$1</h5>');
    preview_text = preview_text.replace( /\[(.*)\]\((.*)\)/g , '<a href="$2">$1</a>' );
    $( '.project-text' ).html(preview_text);



    /* action - btn */
    if($('.action-btn > div').length == 3){
        $('.action-btn').css({width:'85%'});
        $('.action-btn > div').css({width:'calc(100% / 3)'});
    }

});
</script>